In [ ]:
#variable
a=10;
print("I am",a, "years old")

I am 10 years old


In [ ]:
#Arithmetic ooperation on 2 numbers
a=int(input("Enter a number:"))
b=int(input("Enter b number:"))
print("sum is",a+b)
print("difference is",a-b)
print("product is",a*b)
print("quotient is",a/b)
print("remainder is",a%b)
print("power of given number is",a**b)
print("floor is",a//b)

Enter a number:20
Enter b number:15
sum is 35
difference is 5
product is 300
quotient is 1.3333333333333333
remainder is 5
power of given number is 32768000000000000000
floor is 1


In [3]:
#simple if
n=int(input("Enter a number:"))
if(n>0):
  print(n,"is a positive number!!")

Enter a number:7
7 is a positive number!!


In [ ]:
#take a number from a user which is salary.if the salary is morethan 50k,there is a 10% tax.Print his final salary.
a=int(input("Enter your salary:"))
if(a>=50000):
  print("your salary is ",(a-(a/10)))
else:
  print("Your salary is ",a)

Enter your salary:60000
your salary is  54000.0


In [4]:
#get the salary from user if the salary is equal or more than 50k,apply 10% tax detection.if the salary is <50k apply 5% tax.if the salary is >70k apply 12% tax.if yoou r salary exceeds 1 lakh print you are promted to next level.
a=int (input("Enter your salary: "))
if(a==0):
  print("Enter valid salary")
elif(a<50000):
  a=print("your salary is ",a-(a*(5/100)))
elif(a>=50000 and a<=70000):
  a=print("your salary is ",(a-(a*10/100)))
elif(a>70000 and a<=100000):
    a=print("your salary is ",(a-(a*12/100)))
else:
            print("You are promoted!!")




Enter your salary: 85000
your salary is  74800.0


In [ ]:
#for loop
n=int(input("Enter a number:"))
for i in range(1,11):
  print(n,"X", i,"=",n*i)

Enter a number:20
20 X 1 = 20
20 X 2 = 40
20 X 3 = 60
20 X 4 = 80
20 X 5 = 100
20 X 6 = 120
20 X 7 = 140
20 X 8 = 160
20 X 9 = 180
20 X 10 = 200
Enter a number:30


In [ ]:
#while loop
n=int(input("Enter a number:"))
i=1
while (i<11):
  print(n,"X", i,"=",n*i)
  i=i+1

Enter a number:5
5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
5 X 10 = 50


In [ ]:
#list
l1=["soc",1,12.30,False]
for i in l1:
  print(i)

soc
1
12.3
False


In [5]:
list = ["apple", "banana", "cherry"]
print(list[1])

banana


In [6]:
list = ["apple", "banana", "cherry"]
print(list[-1])

cherry


In [ ]:
#list is mutable
#append_adds element @ back of the list
l1.append("True") #listname.append("element")
print(l1)

['soc', 1, 12.3, False, 'True']


In [ ]:
#insert
l=[1,"kill",89,"chat",9.1,True,"append"]
l.insert(4,"insert") #listname.insert(index,element)
print(l)

[1, 'kill', 89, 'chat', 'insert', 9.1, True, 'append']


In [ ]:
#concatination_extend
l2=l1+l
l1.extend(l)  #l1=l1+l  #<list1_name>.extend(<list2_name>)
print(l2)
print(l1)

['soc', 1, 12.3, False, 'True', 1, 'kill', 89, 'chat', 'insert', 9.1, True, 'append']
['soc', 1, 12.3, False, 'True', 1, 'kill', 89, 'chat', 'insert', 9.1, True, 'append']


In [ ]:
#pop an element-will use this function when we know the index of a deleted element
l.pop(2)  #listname.pop(index of the element)
print(l)

[1, 'kill', 'chat', 'insert', 9.1, True, 'append']


In [ ]:
#removing an element_will use this function when we don't know the index
l.remove("kill")  #listname.remove("element")
print(l)


[1, 'chat', 'insert', 9.1, True, 'append']


In [ ]:
#clearing list_the list is cleared but not completely deleted.
l.clear()  #listname.clear()
print(l)

[]


In [ ]:
#create a list of random integers(10 elements).Print their squares and save them in a new list
l1=[1,2,3,4,5,6,7,8,9,10]
l2=[]
for i in l1:
  l2.append(i*i)
print(l2)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
#list_comprehension
#newlist=[output for]  #newlist=[output for if]
l1=[1,2,3,4,5,6,7,8,9,10]
l2=[i**2 for i in l1 if i>5]
print(l2)


[36, 49, 64, 81, 100]


In [ ]:
l1=[1,2,3,4,5,6,7,8,9,10]
l2=[i**2 if i>5 else 'X' for i in l1]   #newlist=[(statement of if) if (cond) else (statement of else) for]
print(l2)


['X', 'X', 'X', 'X', 'X', 36, 49, 64, 81, 100]


In [ ]:
#take the salary from user if salary <50k apply 10% tax otherwise 15% tax
n=int(input("Enter your salary:"))
l1=[]
l1.append(n)
l=[(i-(i*(10/100))) if(i<=50000) else (i-(i*15/100)) for i in l1]
print(l)

Enter your salary:78000
[66300.0]


In [ ]:
salary=[75000,80000,90500,10000,45000]
l=[(i-(i*(10/100))) if(i<=50000) else (i-(i*15/100)) for i in salary]
print(l)

[63750.0, 68000.0, 76925.0, 9000.0, 40500.0]


In [ ]:
#Creating a dictionary
dict1={'Mentor':'Jwalitha','1':'Sahedha', '2':'Praveena','3':'Jyotshna','4':'Tanya'}
print(dict1)

{'Mentor': 'Jwalitha', 1: 'Sahedha', 2: 'Praveena', 3: 'Jyotshna', 4: 'Tanya'}


Dictionary:
dictname={key1:val1,key2:key2.....}

In [ ]:
dict1={'Mentor':'Jwalitha','1':'Sahedha', '2':'Praveena','3':'Jyotshna','4':'Tanya'}
print(dict1.keys())
print(dict1.values())
print(dict1['1'])

dict_keys(['Mentor', '1', '2', '3', '4'])
dict_values(['Jwalitha', 'Sahedha', 'Praveena', 'Jyotshna', 'Tanya'])
Sahedha


In [ ]:
dict2={'Dept':'CSE',"details":{"year":"II","Sec":"D","Count":71}}
print( "Year is",dict2["details"]["year"])
print( "Section is",dict2["details"]["Sec"])
print( "Strength is",dict2["details"]["Count"])

Year is II
Section is D
Strength is 71


In [ ]:
#zipping 2 lists into 1 dictiionary using zip function
l1=[12,34,56,78,90]
l2=["Tanya","Jyotshna","Praveena","Sahedha","Satya"]
l3=zip(l1,l2)
for i in l3:
  print(i)

(12, 'Tanya')
(34, 'Jyotshna')
(56, 'Praveena')
(78, 'Sahedha')
(90, 'Satya')


In [ ]:
#zipping 2 lists into 1 dictiionary using dict keyword
l1=[12,34,56,78,90]
l2=["Tanya","Jyotshna","Praveena","Sahedha","Satya"]
l3=dict(zip(l1,l2))
#l3=dict(zip(l2,l1))
print(l3)

{'Tanya': 12, 'Jyotshna': 34, 'Praveena': 56, 'Sahedha': 78, 'Satya': 90}


In [ ]:
#from main package call sub pakage
import numpy as np
A=np.array([1,2,3,4]) #1d array
print(A.ndim)
print(A.shape)


1
(4,)


In [ ]:
#creating 2d array
A=np.array([[1,2],[3,4],[5,6]]) #elements in each row,columns
print(A.ndim)
print(A.shape)
print(A)


2
(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#creating 3d array
A=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(A.ndim)
print(A.shape)
print(A)
# 1st index indicates that no.of groups, 2nd index indicates that no.of rows,3rd index indicates that no.of columns.
#no.of elements required=(x,y,z)
#for ex(2,2,2)=2*2*2=8 elements required

3
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#2d array
A=np.ones((4,3))  #rows,columns
print(A)
#3d array
A=np.zeros((2,2,3))  #groups,rows,columns
print(A)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
#identity_matrix
A=np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
A=np.arange(1,10,2)  #start,stop,step
print(A)
print(type(A))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
#print all the numbers that are divisible by 8 using arange function beetween 1 & 1000
A=np.arange(8,1001,8)
print(A)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [ ]:
A=np.linspace(50,100,10)
print(A)
#linespace=splitting a range of numbers into n numbers with common differnces

[ 50.          55.55555556  61.11111111  66.66666667  72.22222222
  77.77777778  83.33333333  88.88888889  94.44444444 100.        ]


In [ ]:
#sorting
a=[8,6,4,2,5]
a.sort
print(a)

[8, 6, 4, 2, 5]


In [ ]:
#sorted
a=[8,6,4,2,5]
b=sorted(a)
print(b)

[2, 4, 5, 6, 8]
