In [ ]:
#reshape== changes needs saving in another variable
import numpy as np
A=np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
A=np.linspace(5,13,8).reshape(2,4)
#A=np.arange(1,13).reshape(3,4)
print(A)

[[ 5.          6.14285714  7.28571429  8.42857143]
 [ 9.57142857 10.71428571 11.85714286 13.        ]]


In [ ]:
B=np.array([12,34,56,78,90,13,57,80]).reshape(2,2,2)
print(B)

[[[12 34]
  [56 78]]

 [[90 13]
  [57 80]]]


In [ ]:
#resize==changes the shape of original array
B=np.array([12,34,56,78,90,13,57,80])
B.reshape(2,2,2)
print(B)
B.resize(2,2,2)
print(B)

[12 34 56 78 90 13 57 80]
[[[12 34]
  [56 78]]

 [[90 13]
  [57 80]]]


In [ ]:
A=np.array([34,56,78,90])
B=np.array([3,7,9,12])#list will throwa an error while arrays iterate themselves
C=A-B
print(C)


[31 49 69 78]


In [ ]:
A=np.array([34,56,78,90])
print(A.max())    #max and min accepts only numeric datatypes int and float
print(A.min())


90
34


In [ ]:
A=np.array([34,56,78,90])
B=np.array([3,7,9,12])#list will throwa an error while arrays iterate themselves
C=A+B
print(C)


[ 37  63  87 102]


In [ ]:
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([3,7,9,12]).reshape(2,2) #one on one multiplication
print(A)
print("-----------------")
print(B)
print("-----------------")
C=A*B
print(C)

[[34 56]
 [78 90]]
-----------------
[[ 3  7]
 [ 9 12]]
-----------------
[[ 102  392]
 [ 702 1080]]


In [ ]:
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([3,7,9,12]).reshape(2,2) #one on one multiplication
print(A)
print("-----------------")
print(B)
print("-----------------")
C=A@B
print(C)

[[34 56]
 [78 90]]
-----------------
[[ 3  7]
 [ 9 12]]
-----------------
[[ 606  910]
 [1044 1626]]


In [ ]:
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([3,7,9,12]).reshape(2,2) #one on one multiplication
print(A)
print("-----------------")
print(B)
print("-----------------")
C=A.dot(B)
print(C)

[[34 56]
 [78 90]]
-----------------
[[ 3  7]
 [ 9 12]]
-----------------
[[ 606  910]
 [1044 1626]]


In [ ]:
A=np.array([34,56,78,90]).reshape(2,2)
print(A)
print("---------------------")
print(A.max(axis=0))  #axis=0 --->columns
print("-----------------")
print(A.max(axis=1))  #axis=1 -->row


[[34 56]
 [78 90]]
---------------------
[78 90]
-----------------
[56 90]


In [ ]:
A=np.array([34,56,78,90]).reshape(2,2)
print(A)
print("---------------------")
print(A.min(axis=0))  #axis=0 --->columns
print("-----------------")
print(A.min(axis=1))  #axis=1 -->row


[[34 56]
 [78 90]]
---------------------
[34 56]
-----------------
[34 78]


In [ ]:
#joining arrays
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([3,7,9,12]).reshape(2,2)
print(A)
print("---------------------")
print(B)  #axis=0 --->columns
print("After vertically stacking the arrays!!!")
print(np.vstack((A,B)))  #axis=1 -->row



[[34 56]
 [78 90]]
---------------------
[[ 3  7]
 [ 9 12]]
After vertically stacking the arrays!!!
[[34 56]
 [78 90]
 [ 3  7]
 [ 9 12]]


In [ ]:
#joining arrays
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([3,7,9,12]).reshape(2,2)
print(A)
print("---------------------")
print(B)  #axis=0 --->columns
print("After horizontally stacking the arrays!!!")
print(np.hstack((A,B)))  #axis=1 -->row



[[34 56]
 [78 90]]
---------------------
[[ 3  7]
 [ 9 12]]
After horizontally stacking the arrays!!!
[[34 56  3  7]
 [78 90  9 12]]


In [ ]:
#joining arrays
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([3,7,9,12]).reshape(2,2)
print(A)
print("---------------------")
print(B)  #axis=0 --->columns
print("After stacking the arrays!!!")
print(np.stack((A,B),axis=0))  #axis=1 -->row



[[34 56]
 [78 90]]
---------------------
[[ 3  7]
 [ 9 12]]
After stacking the arrays!!!
[[[34 56]
  [78 90]]

 [[ 3  7]
  [ 9 12]]]


In [ ]:
#joining arrays
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([3,7,9,12]).reshape(2,2)
print(A)
print("---------------------")
print(B)  #axis=0 --->columns
print("After stacking the arrays!!!")
print(np.stack((A,B),axis=1))  #axis=1 -->row



[[34 56]
 [78 90]]
---------------------
[[ 3  7]
 [ 9 12]]
After vertically stacking the arrays!!!
[[[34 56]
  [ 3  7]]

 [[78 90]
  [ 9 12]]]


In [ ]:
#joining arrays using dstack
A=np.arange(30).reshape(2,3,5)  #no.of rows==no.of groups
print(A)                        #no.of columns in every group==no.of rows in every group
                                       # groups  rows  columns
print("After dstack")           #original 2      3      5
print(np.dstack(A))             #dstack   3      5      2


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
After dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#splitting arrays
A=np.arange(18).reshape(6,3)  #np.vsplit(array_name,no.of parts to be divided)
print(A)
print("After splitting")
np.vsplit(A,3)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [ ]:
#splitting arrays
A=np.arange(18).reshape(6,3)  #np.vsplit(array_name,no.of parts to be divided)
print(A)
print("After splitting")
np.vsplit(A,(2,5))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]),
 array([[15, 16, 17]])]

In [ ]:
#splitting arrays
A=np.arange(18).reshape(6,3)  #np.vsplit(array_name,no.of parts to be divided)
print(A)
print("After splitting")
np.vsplit(A,(2,3))       #splitting will be done in row way


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [ ]:
#splitting arrays
A=np.arange(18).reshape(6,3)  #np.vsplit(array_name,no.of parts to be divided)
print(A)
print("After splitting")
np.hsplit(A,3)       #splitting will be done in column way


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12],
        [15]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]])]

In [ ]:
#splitting arrays
A=np.arange(18).reshape(6,3)  #np.vsplit(array_name,no.of parts to be divided)
print(A)
print("After splitting")
np.hsplit(A,(2,3))       #splitting will be done in column way


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13],
        [15, 16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([], shape=(6, 0), dtype=int64)]

In [ ]:
#splitting arrays
A=np.arange(18).reshape(3,6)  #np.vsplit(array_name,no.of parts to be divided)
print(A)
print("After splitting")
np.hsplit(A,(2,3))       #splitting will be done in column way


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
After splitting


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2],
        [ 8],
        [14]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17]])]

In [ ]:
#splitting arrays
A=np.arange(18).reshape(3,6)  #np.vsplit(array_name,no.of parts to be divided)
print(A)
print("After splitting")
np.hsplit(A,3)       #splitting will be done in column way


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
After splitting


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [ ]:
#splitting arrays
A=np.arange(18).reshape(3,6)  #np.vsplit(array_name,no.of parts to be divided)
print(A)
print("After splitting")
np.hsplit(A,(2,5))       #splitting will be done in column way


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
After splitting


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16]]),
 array([[ 5],
        [11],
        [17]])]

In [ ]:
A=np.arange(18).reshape(3,6)
print(A)
print(A.argmax())


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
17


In [ ]:
A=np.arange(18).reshape(3,6)
print(A)                               #position[0 0 0 0
                                                 #1 1 1 1]
print(A.argmax(axis=0))


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[2 2 2 2 2 2]


In [ ]:
A=np.arange(18).reshape(3,6)
print(A)                               #position[0 1 2 3
                                                 #0 1 2 3]
print(A.argmax(axis=1))


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[5 5 5]


In [ ]:
A=np.arange(18).reshape(3,6)
print(A)
print(A.argmin())                      #position[0 1 2 3
                                                 #4 5 6 7]]


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
0


In [ ]:
# numPy statisics
#mean,median,standard deviation,variance
A=np.array([12,34,25,66,71,88])
print("Mean: ",np.mean(A))
print("Median: ",np.median(A))
print("Variance: ",np.var(A))
print("Standard deviation: ",np.std(A))




Mean:  49.333333333333336
Median:  50.0
Variance:  743.888888888889
Standard deviation:  27.274326552435515


Trigonometry

In [ ]:
A=np.pi
print(A)  #radians

3.141592653589793


In [ ]:
np.rad2deg(A)

180.0

In [ ]:
B=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi])
print(B)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
np.rad2deg(B)

array([ 45.,  60.,  90., 180.])

In [ ]:
C=np.array([30,45,60,90,120,180])
D=np.deg2rad(C)
print(D)

[0.52359878 0.78539816 1.04719755 1.57079633 2.0943951  3.14159265]


In [ ]:
C=np.array([0,30,45,60,90,120,180])
np.sin(C)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
        0.58061118, -0.80115264])

In [ ]:
np.cos(C)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
        0.81418097, -0.59846007])

In [ ]:
np.tan(C)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        0.71312301,  1.33869021])

In [ ]:
np.arcsin(1)  #sin^-1

1.5707963267948966

In [ ]:
np.arccos(1)

0.0

In [ ]:
np.arctan(1)

0.7853981633974483

In [ ]:
#searching in array
A=np.array([90,3,45,21,34,90,21])
print(np.where(A==21))


(array([3, 6]),)


In [ ]:
A=np.array([90,3,45,21,34,90,21])
print(np.where(A%2==0))


(array([0, 4, 5]),)


In [ ]:
A=np.array([90,3,45,21,34,90,21])
print(np.where(A>25))


(array([0, 2, 4, 5]),)


In [ ]:
#create a 1D array
import numpy as np
A=np.array([90,3,45,21,34,90,21])
print(np.searchsorted(A,90))  #first the given array will be sorted and then it will search
#3,21,34,45,90--->sorted array
print(np.searchsorted(A,3))

5
0


Linear algebra and ufunction

In [ ]:
A=np.array([6,24,60,12,18])
B=np.array([6,4,10,5,4])
print(np.add(A,B))
print(np.subtract(A,B))
print(np.divide(A,B))
print(np.mod(A,B))
print(np.divmod(A,B))

[12 28 70 17 22]
[ 0 20 50  7 14]
[1.  6.  6.  2.4 4.5]
[0 0 0 2 2]
(array([1, 6, 6, 2, 4]), array([0, 0, 0, 2, 2]))


In [ ]:
print(np.diff(A))

[ 18  36 -48   6]


In [ ]:
A=np.array([6,24,60,12,18])
print(np.sort(A))

[ 6 12 18 24 60]


Set functions!!

In [ ]:
A=np.array([6,24,60,12,18])
B=np.array([6,4,10,5,4])
print(np.union1d(A,B))

[ 4  5  6 10 12 18 24 60]


In [ ]:
A=np.array([6,24,60,12,18])
B=np.array([6,4,10,5,4])
print(np.setdiff1d(A,B))

[12 18 24 60]


In [ ]:
A=np.array([6,24,60,12,18])
B=np.array([6,4,10,5,4])
print(np.intersect1d(A,B))

[6]


In [ ]:
#rounding
#truncating
al=np.trunc([-3.1666,3.6667])
print(al)

[-3.  4.]


In [ ]:
al=np.around([-3.1666,3.6667])
print(al)

[-3.  4.]


In [ ]:
al=np.fix([-3.1666,3.6667])
print(al)

[-3.  3.]


In [ ]:
al=np.ceil([-3.1666,3.6667])
print(al)

[-3.  4.]


In [ ]:
al=np.floor([-3.1666,3.6667])
print(al)

[-4.  3.]


In [ ]:
A=np.array([3,4,16,19,10])
print(np.cumsum(A))

[ 3  7 23 42 52]


In [ ]:
A=np.array([3,4,16,19,10])
print(np.cumsum(A))

In [ ]:
A=np.array([3,4,16,19,10])
print(np.cumprod(A))

[    3    12   192  3648 36480]


In [ ]:
print(np.lcm(34,56))
print(np.gcd(445,655))

952
5


In [ ]:
Ar=([34,45,55,65,75,85])
print(np.lcm.reduce(Ar))
print(np.gcd.reduce(Ar))

1093950
1


In [ ]:
#inverse matrix
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))   #A^-1=(adjacent matrix)/(det of matrix)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#Random_module
from numpy import random as rd

In [ ]:
#random module
A=rd.rand()
print(A)    #rand() is a function whose default value limit is 0 to 0.99

0.16181337669130935


In [ ]:
A=rd.rand(10)
print(A)

[0.97168401 0.060652   0.69078241 0.4053753  0.42791038 0.67553331
 0.86680978 0.2543246  0.80799672 0.08837781]


In [ ]:
A=rd.randint(4)   #limit -->0,1,2,3
print(A)

0


In [ ]:
A=rd.randint(50,size=6)   #(limit,size)
print(A)

[17 35 45  6 33 47]


In [ ]:
A=rd.randint(50,size=(2,3)) #(2,3) indicates no.of rows & no.of columns
print(A)

[[38  5 38]
 [13 18 20]]


JOINS

In [ ]:
A=np.array([1,2,3])
B=np.array([4,5,6])
print(np.inner(A,B))  # the output is given like sum of product of elements-->[(1*4)+(2*5)+(3*6)]=32

32


In [ ]:
A=np.array([1,2,3])
B=np.array([4,5,6])
print(np.outer(A,B))  # the output is given like sum of product of elements-->[(1*4)+(1*5)+(1*6)]->row1
                                                                            #  [(2*4)+(2*5)+(2*6)]->row2
                                                                            #[(3*4)+(3*5)+(3*6)]->row3

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
A=np.array([1,2,3])
B=np.array([4,5,6])
print(np.cross(A,B))  # the output is determinant

[-3  6 -3]
